site_name: 浙江大学新生指引
site_author: mini-full
site_description: 浙江大学本科生新生指引为浙江大学CC98论坛新生宝典版面编撰的新生入学指南。

copyright: Copyright &copy; 2023-present <a href="https://github.com/mini-full" target="_blank" rel="noopener noreferrer">minifull</a>

theme:
  name: material
  language: zh
  logo: assets/校徽_白.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: custom

  
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - navigation.top

    - search.highlight
    - search.share
    - search.suggest


plugins:
  - search:
      lang:
        - zh
        - en


nav:
  - 前言: "preface.md"


extra_css:
  - stylesheets/extra.css
