site_name: 浙江大学新生指南
site_author: mini-full
site_description: 浙江大学本科生新生指引为浙江大学CC98论坛新生宝典版面编撰的新生入学指南。

theme:
  name: material
  language: zh
  logo: assets/校徽.png
  palette:
    primary: custom

nav:
  - 前言: "前言.md"

extra_css:
  - stylesheets/extra.css
